### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Annwenn** [vector-im/vector-web#1046]
As I ran `npm run build`, I saw a (non-fatal) error during the building process: 
```
ERROR in ./~/matrix-react-sdk/~/highlight.js/lib/languages/autoit.js
Module parse failed: /home/uniaika/websites/vector-web/node_modules/source-map-loader/index.js!/home/uniaika/websites/vector-web/node_modules/matrix-react-sdk/node_module
s/highlight.js/lib/languages/autoit.js Maximum call stack size exceeded
You may need an appropriate loader to handle this file type.
RangeError: Maximum call stack size exceeded
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:44:35)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/home/uniaika/websites/vector-web/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/home/uniaika/websites/vector-web/node_modules/webpack/lib/Parser.js:60:20)
 @ ./~/matrix-react-sdk/~/highlight.js/lib/index.js 13:32-61

```

**Comment by ara4n** [comment]
This is a bug in webpack: https://github.com/webpack/webpack/issues/1721. The workaround for now is to keep building until you get lucky and it works :(

**Comment by richvdh** [comment]
this can't possibly be a p1

**Comment by richvdh** [comment]
Hopefully fixed by https://github.com/vector-im/vector-web/issues/1277

**Comment by Annwenn** [comment]
Thanks :)
