### ISSUE TITLE
Room can get stuck incapable of scrolling to the bottom

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1389]
* I unslept my mac
* Whilst it was catching up, switched to a busy room (#irc:matrix.org)
* It jumped me to an offset from where I last read the room - possibly because I had scrolled up when I was last looking at it
* I tried to scroll downwards; hit the limit of the current timeline window; started to paginate forwards
* Kept paginating forwards until I caught up with the current time, but "(v) 20 unread messages" was still present.
* Clicked on the "20 unread messages" prompt.  Jumped me to the bottom, but the prompt didn't go away, and instead it tried to do a forward pagination (spinner), which then disappeared leaving you at the bottom.
* Switched room and back again
* Now saw "(v)" jump to bottom prompt (no unread messages)
* Clicking on this prompt again triggers a forward pagination that goes nowhere and leaves you stranded there.

**Comment by richvdh** [comment]
I think this might have happened because the pagination got to the end of the live timeline before your  sync completed.

I added some sanity checking to the js-sdk today, which might make things blow up in a more meaningful way when this happens.

**Comment by richvdh** [comment]
Saw something rather similar to this today; console logs are:

```
index.js:149 newscreen room/#irc:matrix.org
2016-07-14 22:43:58.663 RoomView.js:1230 updateTint from RoomView._gatherTimelinePanelRef
2016-07-14 22:43:58.663 RoomView.js:382 Tinter.tint from updateTint
2016-07-15 09:28:51.584 sync.js:533 /sync error MatrixError(anonymous function) @ sync.js:533
2016-07-15 09:28:51.601 sync.js:534 MatrixErrordata: Objecterrcode: "ORG.MATRIX.JSSDK_TIMEOUT"message: "Locally timed out waiting for a response"name: "ORG.MATRIX.JSSDK_TIMEOUT"__proto__: Error(anonymous function) @ sync.js:534
2016-07-15 09:28:51.601 sync.js:21 Starting keep-alive
2016-07-15 09:28:51.607 MatrixChat.js:584 MatrixClient sync state => ERROR
2016-07-15 09:28:57.705 https://matrix.sw1v.org/_matrix/client/versions? Failed to load resource: net::ERR_INTERNET_DISCONNECTED
2016-07-15 09:29:08.425 sync.js:511 Caught /sync error TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Object.module.exports.deepCopy (https://vector.im/develop/bundle.js:9242:29)
    at EventTimeline.initialiseState (https://vector.im/develop/bundle.js:18395:16)
    at Room.resetLiveTimeline (https://vector.im/develop/bundle.js:29289:18)
    at https://vector.im/develop/bundle.js:86382:23
    at Array.forEach (native)
    at SyncApi._processSyncResponse (https://vector.im/develop/bundle.js:86313:16)
    at https://vector.im/develop/bundle.js:86205:19
    at _fulfilled (https://vector.im/develop/bundle.js:1746:55)
    at self.promiseDispatch.done (https://vector.im/develop/bundle.js:1775:31)(anonymous function) @ sync.js:511
2016-07-15 09:29:08.426 MatrixChat.js:584 MatrixClient sync state => SYNCING
2016-07-15 09:29:39.770 room.js:583 Already have timeline for $1468517651563438DnFQq:matrix.org - joining timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T20:31:37.269Z to !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.771 room.js:556 Event $1468517650563436zcGyb:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.771 room.js:556 Event $1468516884561617MHNaF:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.771 room.js:556 Event $1468516863561565CxjyU:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.772 room.js:556 Event $1468516688561168FyZII:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.772 room.js:556 Event $1468516682561156MnmUu:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.772 room.js:556 Event $1468516678561148ppZke:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.772 room.js:556 Event $1468516676561145SVABT:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.772 room.js:556 Event $1468516491560674autcH:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.772 room.js:556 Event $1468516476560651PuaKt:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:39.772 room.js:556 Event $1468516440560543edYJQ:matrix.org already in timeline !SudviOJlimDvrGdFCY:matrix.org:2016-07-14T08:53:45.095Z
2016-07-15 09:29:40.371 https://matrix.sw1v.org/_matrix/media/v1/thumbnail/sw1v.org/czlMgUONNCqcvrvhPzXanKOg?width=100&height=100 Failed to load resource: the server responded with a status of 404 (Not Found)
2016-07-15 09:29:42.910 index.js:149 newscreen room/#matrix-dev:matrix.org
2016-07-15 09:29:43.112 RoomView.js:1230 updateTint from RoomView._gatherTimelinePanelRef
2016-07-15 09:29:43.112 RoomView.js:382 Tinter.tint from updateTint
2016-07-15 09:29:43.730 https://matrix.sw1v.org/_matrix/media/r0/preview_url?url=http%3A%2F%2Fexamp…Tk4MzYzNjYKMDAyZnNpZ25hdHVyZSCoXpXgt5BFo2D7VIZtNoUjGvrht195g7OWXfXDcUEyXgo Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2016-07-15 09:29:43.732 InviteMemberList.js:110 Failed to get preview for http://example.com/$eventId:example.com M_UNKNOWN: Failed to download content: 502: Got error 404(anonymous function) @ InviteMemberList.js:110
2016-07-15 09:29:50.120 index.js:149 newscreen room/#matrix:matrix.org
2016-07-15 09:29:50.328 RoomView.js:1230updateTint from RoomView._gatherTimelinePanelRef
2016-07-15 09:29:50.328 RoomView.js:382Tinter.tint from updateTint
2016-07-15 09:29:51.104 q.js:161Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-15 09:29:51.231 q.js:161 Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-15 09:30:05.633 sync.js:511Caught /sync error Error: live timeline is no longer live - it has a pagination token (s652567_2391735_33755_614623_40_86)
    at Room.addLiveEvents (https://vector.im/develop/bundle.js:30014:16)
    at SyncApi._processRoomEvents (https://vector.im/develop/bundle.js:86668:11)
    at https://vector.im/develop/bundle.js:86387:15
    at Array.forEach (native)
    at SyncApi._processSyncResponse (https://vector.im/develop/bundle.js:86313:16)
    at https://vector.im/develop/bundle.js:86205:19
    at _fulfilled (https://vector.im/develop/bundle.js:1746:55)
    at self.promiseDispatch.done (https://vector.im/develop/bundle.js:1775:31)
    at Promise.promise.promiseDispatch (https://vector.im/develop/bundle.js:1708:14)
    at https://vector.im/develop/bundle.js:1516:45(anonymous function) @ sync.js:511
2016-07-15 09:30:06.271 sync.js:511Caught /sync error Error: live timeline is no longer live - it has a pagination token (s652567_2391735_33755_614623_40_86)
    at Room.addLiveEvents (https://vector.im/develop/bundle.js:30014:16)
    at SyncApi._processRoomEvents (https://vector.im/develop/bundle.js:86668:11)
    at https://vector.im/develop/bundle.js:86387:15
    at Array.forEach (native)
    at SyncApi._processSyncResponse (https://vector.im/develop/bundle.js:86313:16)
    at https://vector.im/develop/bundle.js:86205:19
    at _fulfilled (https://vector.im/develop/bundle.js:1746:55)
    at self.promiseDispatch.done (https://vector.im/develop/bundle.js:1775:31)
    at Promise.promise.promiseDispatch (https://vector.im/develop/bundle.js:1708:14)
    at https://vector.im/develop/bundle.js:1516:45(anonymous function) @ sync.js:511_fulfilled @ q.js:834self.promiseDispatch.done @ q.js:863Promise.promise.promiseDispatch @ q.js:796(anonymous function) @ q.js:604runSingle @ q.js:137flush @ q.js:125onNextTick @ main.js:36Item.run @ browser.js:67drainQueue @ browser.js:37
2016-07-15 09:30:33.059 sync.js:511 Caught /sync error Error: live timeline is no longer live - it has a pagination token (s652567_2391735_33755_614623_40_86)
    at Room.addLiveEvents (https://vector.im/develop/bundle.js:30014:16)
    at SyncApi._processRoomEvents (https://vector.im/develop/bundle.js:86668:11)
    at https://vector.im/develop/bundle.js:86387:15
    at Array.forEach (native)
    at SyncApi._processSyncResponse (https://vector.im/develop/bundle.js:86313:16)
    at https://vector.im/develop/bundle.js:86205:19
    at _fulfilled (https://vector.im/develop/bundle.js:1746:55)
    at self.promiseDispatch.done (https://vector.im/develop/bundle.js:1775:31)
    at Promise.promise.promiseDispatch (https://vector.im/develop/bundle.js:1708:14)
    at https://vector.im/develop/bundle.js:1516:45(anonymous function) @ sync.js:511_fulfilled @ q.js:834self.promiseDispatch.done @ q.js:863Promise.promise.promiseDispatch @ q.js:796(anonymous function) @ q.js:604runSingle @ q.js:137flush @ q.js:125onNextTick @ main.js:36Item.run @ browser.js:67drainQueue @ browser.js:37

... (repeats)
```

**Comment by richvdh** [comment]
![screenshot_2016-07-15_09-43-40](https://cloud.githubusercontent.com/assets/1389908/16868629/a88627c0-4a70-11e6-9763-e7982613c23c.png)

**Comment by ara4n** [comment]
I saw somethig like this yesterday too (wonder if we have a regression?)

The room had been scrolled back a bit; the comp was slept; on waking up lots of new messages in the room but the roomview got stuck on forwards paginating with a spinner at the bottom of the room that never went away.

**Comment by richvdh** [comment]
I don't really think it's a regression - I just think it's an edge case in the timeline logic which doesn't get hit very often.

**Comment by richvdh** [comment]
In this case I think things started going wrong with that "2016-07-15 09:29:08.425 sync.js:511 Caught /sync error TypeError: Converting circular structure to JSON". Can't really imagine what could cause that.

**Comment by ara4n** [comment]
I was in a rush and didn't get logs; mea culpa.

**Comment by ara4n** [comment]
Just saw this again, this time with logs!  This was first time on unsleeping vector since 2am - includes activity from 2am for context (and the comp managing to occasionally mysteriously wake up to do stuff whilst asleep until I turned it back on at ~23:35):

```
index.js:118 Routing URL https://vector.im/develop/#/room/#vector:matrix.org
2016-07-30 02:09:39.183 PasswordReset.js:81 Presence: online
2016-07-30 02:10:03.567 base-apis.js:533 Failed to decrypt with an existing session: OLM.BAD_MESSAGE_MAC
2016-07-30 02:10:03.578 base-apis.js:533 Failed to decrypt with an existing session: OLM.BAD_MESSAGE_MAC
2016-07-30 02:10:06.024 MatrixChat.js:494 MatrixClient sync state => PREPARED
2016-07-30 02:10:06.231 MatrixChat.js:494 MatrixClient sync state => SYNCING
2016-07-30 02:10:06.804 RoomView.js:1176 updateTint from RoomView._gatherTimelinePanelRef
2016-07-30 02:10:06.804 RoomView.js:338 Tinter.tint from updateTint
2016-07-30 02:15:13.094 PasswordReset.js:81 Presence: unavailable
2016-07-30 14:24:20.908 sync.js:441 /sync error Error: CORS request rejected: https://matrix.org/_matrix/client/r0/sync?filter=21&timeout=30000&since=s32…gzNzA2MDM1CjAwMmZzaWduYXR1cmUgFvDijWZSGyig_37n17-5KQqVz4jmYV1kkazLihMp6FwK
    at on_response (https://vector.im/develop/bundle.js:41672:23)
    at XMLHttpRequest.on_state_change (https://vector.im/develop/bundle.js:41655:8)(anonymous function) @ sync.js:441
2016-07-30 14:24:20.908 sync.js:442 Error: CORS request rejected: https://matrix.org/_matrix/client/r0/sync?filter=21&timeout=30000&since=s32…gzNzA2MDM1CjAwMmZzaWduYXR1cmUgFvDijWZSGyig_37n17-5KQqVz4jmYV1kkazLihMp6FwK(…)(anonymous function) @ sync.js:442
2016-07-30 14:24:20.908 webstorage.js:620 Starting keep-alive
2016-07-30 14:24:20.913 MatrixChat.js:494 MatrixClient sync state => ERROR
2016-07-30 14:24:31.991 MatrixChat.js:494 MatrixClient sync state => SYNCING
2016-07-30 17:24:55.584 sync.js:441 /sync error MatrixError(anonymous function) @ sync.js:441
2016-07-30 17:24:55.584 sync.js:442 MatrixError(anonymous function) @ sync.js:442
2016-07-30 17:24:55.585 webstorage.js:620 Starting keep-alive
2016-07-30 17:24:55.587 MatrixChat.js:494 MatrixClient sync state => ERROR
2016-07-30 19:13:05.707 MatrixChat.js:494 MatrixClient sync state => SYNCING
2016-07-30 21:01:14.003 http-api.js:334 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
2016-07-30 21:01:14.003 http-api.js:334 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
2016-07-30 21:01:14.793 room.js:586 Already have timeline for $1469898599719735YwiGl:matrix.org - joining timeline !DgvjtOljKujDBrxyHk:matrix.org:2016-07-30T19:01:11.589Z to !DgvjtOljKujDBrxyHk:matrix.org:2016-07-30T00:10:03.029Z
2016-07-30 22:49:17.266 sync.js:441 /sync error MatrixError(anonymous function) @ sync.js:441
2016-07-30 22:49:17.269 sync.js:442 MatrixError(anonymous function) @ sync.js:442
2016-07-30 22:49:17.269 webstorage.js:620 Starting keep-alive
2016-07-30 22:49:17.336 MatrixChat.js:494 MatrixClient sync state => ERROR
2016-07-30 23:00:09.855 sync.js:419 Caught /sync error TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Object.module.exports.deepCopy (https://vector.im/develop/bundle.js:9257:29)
    at EventTimeline.initialiseState (https://vector.im/develop/bundle.js:18497:16)
    at Room.resetLiveTimeline (https://vector.im/develop/bundle.js:29365:18)
    at https://vector.im/develop/bundle.js:86810:23
    at Array.forEach (native)
    at SyncApi._processSyncResponse (https://vector.im/develop/bundle.js:86741:16)
    at https://vector.im/develop/bundle.js:86621:19
    at _fulfilled (https://vector.im/develop/bundle.js:1738:55)
    at self.promiseDispatch.done (https://vector.im/develop/bundle.js:1767:31)(anonymous function) @ sync.js:419
2016-07-30 23:00:09.858 MatrixChat.js:494 MatrixClient sync state => SYNCING
2016-07-30 23:36:54.726 sync.js:441 /sync error MatrixError(anonymous function) @ sync.js:441
2016-07-30 23:36:54.728 sync.js:442 MatrixError(anonymous function) @ sync.js:442
2016-07-30 23:36:54.728 webstorage.js:620 Starting keep-alive
2016-07-30 23:36:54.822 MatrixChat.js:494 MatrixClient sync state => ERROR
2016-07-30 23:37:00.857 sync.js:419 Caught /sync error Error: live timeline is no longer live - it has a pagination token (s32122038_16245537_127754_2761035_10693_6883)
    at Room.addLiveEvents (https://vector.im/develop/bundle.js:30090:16)
    at SyncApi._processRoomEvents (https://vector.im/develop/bundle.js:87096:11)
    at https://vector.im/develop/bundle.js:86815:15
    at Array.forEach (native)
    at SyncApi._processSyncResponse (https://vector.im/develop/bundle.js:86741:16)
    at https://vector.im/develop/bundle.js:86621:19
    at _fulfilled (https://vector.im/develop/bundle.js:1738:55)
    at self.promiseDispatch.done (https://vector.im/develop/bundle.js:1767:31)
    at Promise.promise.promiseDispatch (https://vector.im/develop/bundle.js:1700:14)
    at https://vector.im/develop/bundle.js:1508:45(anonymous function) @ sync.js:419
2016-07-30 23:37:00.859 MatrixChat.js:494 MatrixClient sync state => SYNCING
2016-07-30 23:37:01.067 PasswordReset.js:81 Presence: online
2016-07-30 23:38:33.160 sync.js:419 Caught /sync error Error: live timeline is no longer live - it has a pagination token (s32122038_16245537_127754_2761035_10693_6883)
    at Room.addLiveEvents (https://vector.im/develop/bundle.js:30090:16)
    at SyncApi._processRoomEvents (https://vector.im/develop/bundle.js:87096:11)
    at https://vector.im/develop/bundle.js:86815:15
    at Array.forEach (native)
    at SyncApi._processSyncResponse (https://vector.im/develop/bundle.js:86741:16)
    at https://vector.im/develop/bundle.js:86621:19
    at _fulfilled (https://vector.im/develop/bundle.js:1738:55)
    at self.promiseDispatch.done (https://vector.im/develop/bundle.js:1767:31)
    at Promise.promise.promiseDispatch (https://vector.im/develop/bundle.js:1700:14)
    at https://vector.im/develop/bundle.js:1508:45(anonymous function) @ sync.js:419
2016-07-30 23:38:51.894 index.js:149 newscreen room/#matrix:matrix.org
2016-07-30 23:38:52.186 RoomView.js:1176 updateTint from RoomView._gatherTimelinePanelRef
2016-07-30 23:38:52.186 RoomView.js:338Tinter.tint from updateTint
2016-07-30 23:38:52.594 q.js:161Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-30 23:38:53.134 q.js:161Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-30 23:38:59.361 q.js:161Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-30 23:39:10.406 index.js:149newscreen room/#vector:matrix.org
2016-07-30 23:39:10.587 bundle.js:93644 updateTint from RoomView._gatherTimelinePanelRef
2016-07-30 23:39:10.587 bundle.js:92799 Tinter.tint from updateTint
2016-07-30 23:39:32.083 bundle.js:187 newscreen room/#matrix:matrix.org
2016-07-30 23:39:32.280 bundle.js:93644 updateTint from RoomView._gatherTimelinePanelRef
2016-07-30 23:39:32.280 bundle.js:92799 Tinter.tint from updateTint
2016-07-30 23:39:32.650 bundle.js:1065 Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-30 23:39:34.318 bundle.js:1065 Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-30 23:39:34.598 bundle.js:1065 Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-30 23:39:34.735 bundle.js:1065 Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-30 23:39:35.177 bundle.js:1065 Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents instead
2016-07-30 23:39:37.641 room.js:461Uncaught Error: Room.addEventsToTimeline cannot be used for adding events to the live timeline - use Room.addLiveEvents insteadRoom.addEventsToTimeline @ room.js:461(anonymous function) @ client.js:2658_fulfilled @ q.js:834self.promiseDispatch.done @ q.js:863Promise.promise.promiseDispatch @ q.js:796(anonymous function) @ q.js:604runSingle @ q.js:137flush @ q.js:125onNextTick @ main.js:39Item.run @ browser.js:43drainQueue @ browser.js:13
```

**Comment by ara4n** [comment]
The circular structure here is presumably going to be some kind of should-have-cloned fail. @Kegsay, don't suppose you know what could be causing this?

**Comment by Kegsay** [comment]
> what could be causing this?

`deepCopy` simply doesn't support circular refs, as mentioned in the docs - https://github.com/matrix-org/matrix-js-sdk/blob/master/lib/utils.js#L240

It looks like `stateEvents` has the aforementioned circular refs, but it shouldn't - https://github.com/matrix-org/matrix-js-sdk/blob/2c40932080f6da287c7e5fa9633391cac3093424/lib/models/event-timeline.js#L79

It looks like it is being populated here - https://github.com/matrix-org/matrix-js-sdk/blob/09d08a50920083e6b318c0a4f112412304b41789/lib/models/room.js#L231

Which is interesting because it is pulling that from the latest state - https://github.com/matrix-org/matrix-js-sdk/blob/09d08a50920083e6b318c0a4f112412304b41789/lib/models/room.js#L225

Which makes me think that something is being naughty and creating a circular ref inside the `event` property of a `MatrixEvent` which is in `currentState` on a room.

**Comment by Kegsay** [comment]
A quick grep for likely candidates in JS SDK, React SDK and Vector turned up nothing. If you're serious about investigating the circular refs thing, I would try:
 - Login to a local client on a local HS, join a room and send some messages.
 - Artificially kill your connection on the browser in chrome dev tools.
 - Using another client, flood the room with lots of messages.
 - Regain your connection, which should for `/sync` to return a `limited` response.
 - Make sure it is not getting the circular ref error. If it is, you can use `require("util").inspect(object)` which **will** work on circular refs and allow you to see what key is being added to the raw event and narrow down your culprits.
 - If it isn't getting a circular ref error, then there must be something else which is triggering it (maybe an unsent message, encrypted message, anything which may want to cache operations in relation to an event).

**Comment by ara4n** [comment]
@wmwragg is seeing this too

**Comment by Kegsay** [comment]
The quick and dirty way to isolate this would be to wrap the innards of `deepCopy` in a `try/catch` and in the catch block log what the object is via `require("util").inspect(object)` and then re-throw to die. That way we will be able to see exactly what Object has the circular loop, and avoids needless logging spam.

**Comment by richvdh** [comment]
It looks like the thing that causes this is a redaction of a state event (such as `m.room.member`) followed by a limited sync.

The problem was introduced by https://github.com/matrix-org/matrix-js-sdk/pull/80, which adds the `MatrixEvent` for the redaction event to the raw event data of the redacted event. We then end up trying to deep-copy the MatrixEvent when we get the limited sync, leading to this problem.
