### ISSUE TITLE
Initial /sync can crash out with megolm errors, leaving you with no visible rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2160]
stacktrace from current /develop is:

```
sync.js:511 Caught /sync error Error: OLM.BAD_SESSION_KEY
    at Error (native)
    at https://vector.im/develop/olm.js:14:137
    at Q.<anonymous> (https://vector.im/develop/olm.js:310:104)
    at Q.create (https://vector.im/develop/olm.js:14:402)
    at OlmDevice.addInboundGroupSession (https://vector.im/develop/bundle.js:105269:18)
    at MegolmDecryption.onRoomKeyEvent (https://vector.im/develop/bundle.js:105784:22)
    at Crypto._onRoomKeyEvent (https://vector.im/develop/bundle.js:106924:10)
    at MatrixClient.<anonymous> (https://vector.im/develop/bundle.js:106118:21)
    at MatrixClient.EventEmitter.emit (https://vector.im/develop/bundle.js:19045:18)
    at https://vector.im/develop/bundle.js:109946:29
```

**Comment by ara4n** [comment]
also just had this as a catchup sync, leaving chunks of history missing :(

**Comment by NegativeMjark** [comment]
I think this should be fixed by the try/catch blocks.
