### ISSUE TITLE
Error handling when 3PID invites fail is nonexistent (and it's failing for me atm)

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#848]
If I create a private room and invite a 3PID into it (e.g. matthew at arasphere dot net), the `/invite` fails with a 401 from synapse and the invite fails silently in Vector.

**Comment by ara4n** [comment]
The synapse side of this is:

```
2016-02-02 18:50:13,375 - synapse.access.https.8448 - 483 - INFO - PUT-233893 - 127.0.0.1 - 8448 - Received request: PUT /_matrix/federation/v1/invite/!WWeQOmtuitDHSbqYOi:matrix.org/$145443901314694OeDQk:matrix.org
2016-02-02 18:50:13,376 - synapse.federation.transport.server - 156 - ERROR - PUT-233893 - authenticate_request failed
Traceback (most recent call last):
  File "synapse/federation/transport/server.py", line 149, in new_code
    (origin, content) = yield authenticator.authenticate_request(request)
SynapseError: 401: Invalid signature for server matrix.org with key ed25519:auto
```

The vector side is just exposing that 401 sensibly.

**Comment by ara4n** [comment]
Apparently this was because `matthew at arasphere dot net` mapped to @matthew:localhost in the sydent db, so matrix.org tried to talk to itself and got confused.  I then deleted the mapping from the sydent db (global & local tables) and tried again.  This time it failed with a 500 - again, silent failure in vector.  Synapse had:

```
2016-02-02 22:36:40,084 - synapse.http.server - 125 - ERROR - POST-531443 - Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x542d250>: <XForwardedForRequest at 0x473631b8 method=POST uri=/_matrix/client/api/v1/rooms
/!WWeQOmtuitDHSbqYOi:matrix.org/invite?access_token=<redacted> clientproto=HTTP/1.1 site=8080>
Traceback (most recent call last):
  File "synapse/http/server.py", line 104, in wrapped_request_handler
    yield d
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/http/server.py", line 235, in _async_render
    callback_return = yield callback(request, *args)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/rest/client/v1/room.py", line 469, in on_POST
    txn_id
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/handlers/room.py", line 703, in do_3pid_invite
    txn_id=txn_id
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/handlers/room.py", line 809, in _make_and_store_3pid_invite
    inviter_avatar_url=inviter_avatar_url
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "synapse/handlers/room.py", line 865, in _ask_id_server_for_third_party_invite
    display_name = data["display_name"]
KeyError: 'display_name'
```

**Comment by ara4n** [comment]
So digging in further, as the error suggests, it's because the response to /store-invite on the IS is failing to return a display_name.  Looking at the code on the live matrix.org sydent, it's indeed stale, and doesn't return a display_name (this seems to have been added in https://github.com/matrix-org/sydent/commit/f14657877684fe40d5d3dd0f7cd10c3c93eb3621#diff-02db4ed53efd71fd5703002ed87985fbR72).

I am totally confused on how this could ever have worked?  Or why it's talking to the matrix.org IS rather than the vector.im one?

**Comment by illicitonion** [comment]
It uses whichever IS you specify on the login page. I believe @dbkr was the person to deploy the changes, I thought he did to both, and @Kegsay has been testing manually; don't know whether he has been setting one IS or another explicitly...

**Comment by ara4n** [comment]
empirically it doesn't; my IS on advanced options is the default: vector.im. Except it's talking to the old matrix.org HS instead.

**Comment by Kegsay** [comment]
I've not been touching the IS URL in my manual testing because I have no clue what it should be, so I leave it as it is.

**Comment by dbkr** [comment]
The actual bug we're concerned about here seems to be that if you invite someone with an email address they're not signed up to Matrix with, they click the link to open a vector with an existing session, they are left with an infinite spinner and a 400 bad request error in the console.
